import { Asap } from "next/font/google";
import NavBar from "@/components/navbar";
import { getServerSession } from "next-auth";
import { authOption } from "@/lib/auth";
import { User } from "next-auth";
const asap = Asap({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOption);
  const user = session?.user;
  return (
    <>
      <div>
        <NavBar user={user} />
      </div>
      <main className="h-[calc(100%-40px)]">{children}</main>
    </>
  );
}
