import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { Asap } from "next/font/google";
import NavBar from "@/components/navbar";

const asap = Asap({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${asap.className} scrollbar`}>
        <main className="h-[100%] p-3">{children}</main> <Toaster />
      </body>
    </html>
  );
}
